// Code generated by scripts/generate-constants.ts; DO NOT EDIT.

package aid

// ---------------------------------------------------------------------------
// Version
// ---------------------------------------------------------------------------

const SpecVersionV1 = "aid1"
const SpecVersionV2 = "aid2"
const SpecVersion = "aid2"

var SupportedSpecVersions = []string{
	"aid1",
	"aid2",
}

// Version-specific raw record metadata. AidRecordV2 excludes legacy DNS kid/i.
var AidRecordV1CanonicalFields = []string{
	"v",
	"uri",
	"proto",
	"auth",
	"desc",
	"docs",
	"dep",
	"pka",
	"kid",
}
var AidRecordV1AliasFields = []string{
	"p",
	"u",
	"a",
	"s",
	"d",
	"e",
	"k",
	"i",
}
var AidRecordV2CanonicalFields = []string{
	"v",
	"uri",
	"proto",
	"auth",
	"desc",
	"docs",
	"dep",
	"pka",
}
var AidRecordV2AliasFields = []string{
	"p",
	"u",
	"a",
	"s",
	"d",
	"e",
	"k",
}

// ---------------------------------------------------------------------------
// Protocol tokens
// ---------------------------------------------------------------------------
const (
	ProtoA2a       = "a2a"
	ProtoGraphql   = "graphql"
	ProtoGrpc      = "grpc"
	ProtoLocal     = "local"
	ProtoMcp       = "mcp"
	ProtoOpenapi   = "openapi"
	ProtoUcp       = "ucp"
	ProtoWebsocket = "websocket"
	ProtoZeroconf  = "zeroconf"
)

// ProtocolTokens maps protocol names to their string representation
var ProtocolTokens = map[string]string{
	"a2a":       "a2a",
	"graphql":   "graphql",
	"grpc":      "grpc",
	"local":     "local",
	"mcp":       "mcp",
	"openapi":   "openapi",
	"ucp":       "ucp",
	"websocket": "websocket",
	"zeroconf":  "zeroconf",
}

// ---------------------------------------------------------------------------
// Auth tokens
// ---------------------------------------------------------------------------
const (
	AuthApikey       = "apikey"
	AuthBasic        = "basic"
	AuthCustom       = "custom"
	AuthMtls         = "mtls"
	AuthNone         = "none"
	AuthOauth2Code   = "oauth2_code"
	AuthOauth2Device = "oauth2_device"
	AuthPat          = "pat"
)

// AuthTokens maps auth token names to their string representation
var AuthTokens = map[string]string{
	"apikey":        "apikey",
	"basic":         "basic",
	"custom":        "custom",
	"mtls":          "mtls",
	"none":          "none",
	"oauth2_code":   "oauth2_code",
	"oauth2_device": "oauth2_device",
	"pat":           "pat",
}

// ---------------------------------------------------------------------------
// Error codes
// ---------------------------------------------------------------------------
const (
	ErrDnsLookupFailed  = 1004
	ErrFallbackFailed   = 1005
	ErrInvalidTxt       = 1001
	ErrNoRecord         = 1000
	ErrSecurity         = 1003
	ErrUnsupportedProto = 1002
)

// ErrorMessages maps error codes to their human-readable descriptions
var ErrorMessages = map[int]string{
	ErrDnsLookupFailed:  "The DNS query failed for a network-related reason",
	ErrFallbackFailed:   "The .well-known fallback failed or returned invalid data",
	ErrInvalidTxt:       "A record was found but is malformed or missing required keys",
	ErrNoRecord:         "No _agent TXT record was found for the domain",
	ErrSecurity:         "Discovery failed due to a security policy (e.g., DNSSEC failure, local execution denied)",
	ErrUnsupportedProto: "The record is valid, but the client does not support the specified protocol",
}

// ---------------------------------------------------------------------------
// Other spec constants
// ---------------------------------------------------------------------------

const DnsSubdomain = "_agent"
const DnsTtlMin = 300
const DnsTtlMax = 900

// LocalURISchemes contains the allowed URI schemes for local protocol
var LocalUriSchemes = []string{
	"docker",
	"npx",
	"pip",
}
