/**
 * Documentation content loader.
 *
 * Primary: reads a pre-compiled JSON index generated by
 *   scripts/generate-docs-index.ts (required for Cloudflare Workers, where
 *   `fs` is unavailable at runtime).
 *
 * Fallback: if the pre-compiled index is missing (e.g., local dev before
 *   running the generator), reads markdown from packages/docs via fs. This
 *   path never executes on Cloudflare Workers because the generator always
 *   runs as part of `build:cf`.
 */

import { preprocessMarkdown } from './markdown';

export interface Heading {
  depth: number; // 2–6
  text: string;
  id: string;
}

export interface DocPage {
  slug: string; // "index" for root; e.g. "quickstart/quickstart_ts" otherwise
  title: string;
  description: string;
  content: string; // preprocessed markdown
  rawContent: string; // original raw markdown
  headings: Heading[];
}

interface DocsIndexShape {
  fileSlugs: string[];
  docsByRouteSlug: Record<string, DocPage>;
  navigation: {
    rootPages: Array<{ title: string; slug: string }>;
    groups: Array<{
      title: string;
      slug: string;
      items: Array<{ title: string; slug: string }>;
    }>;
  };
}

let _index: DocsIndexShape | null = null;

function getIndex(): DocsIndexShape | null {
  if (_index) return _index;
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    _index = require('../../generated/docs-index.json') as DocsIndexShape;
    return _index;
  } catch {
    return null;
  }
}

// --- Internal helper shared with navigation.ts via re-export ---
export function _getIndex(): DocsIndexShape | null {
  return getIndex();
}

// ---------- fs fallback (local dev only) ----------

function toRouteSlug(slug: string): string {
  if (slug === 'index') return 'index';
  if (slug.endsWith('/index')) return slug.slice(0, -'/index'.length);
  return slug;
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replaceAll(/[^\w\s-]/g, '')
    .replaceAll(/\s+/g, '-')
    .replaceAll(/-+/g, '-')
    .trim();
}

function extractHeadings(content: string): Heading[] {
  const headings: Heading[] = [];
  for (const line of content.split('\n')) {
    const match = line.match(/^(#{2,6})\s+(.+)/);
    if (match) {
      const depth = match[1].length;
      const text = match[2]
        .replaceAll(/`([^`]*)`/g, '$1')
        .replaceAll(/\*\*([^*]*)\*\*/g, '$1')
        .replaceAll(/\*([^*]*)\*/g, '$1')
        .trim();
      headings.push({ depth, text, id: slugify(text) });
    }
  }
  return headings;
}

function getDocFromFs(slug: string): DocPage | null {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const fs = require('node:fs') as typeof import('node:fs');
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const path = require('node:path') as typeof import('node:path');
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const matter = require('gray-matter') as typeof import('gray-matter');

    const docsDir = fs.existsSync(path.join(process.cwd(), 'packages', 'docs'))
      ? path.join(process.cwd(), 'packages', 'docs')
      : path.join(process.cwd(), '..', 'docs');

    const normalized = slug.replaceAll(/^\/+|\/+$/g, '');
    const candidates = normalized ? [normalized, `${normalized}/index`] : ['index'];

    let fileSlug: string | null = null;
    for (const candidate of candidates) {
      if (fs.existsSync(path.join(docsDir, `${candidate}.md`))) {
        fileSlug = candidate;
        break;
      }
    }
    if (!fileSlug) return null;

    const routeSlug = toRouteSlug(fileSlug);
    const raw = fs.readFileSync(path.join(docsDir, `${fileSlug}.md`), 'utf8');
    const { data, content: rawBody } = matter(raw);

    const title = (data.title as string) || routeSlug.split('/').pop() || routeSlug || 'index';
    const description = (data.description as string) ?? '';
    return {
      slug: routeSlug === '' ? 'index' : routeSlug,
      title,
      description,
      content: preprocessMarkdown(rawBody, fileSlug),
      rawContent: rawBody,
      headings: extractHeadings(rawBody),
    };
  } catch {
    return null;
  }
}

function getAllDocSlugsFromFs(): string[] {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const fs = require('node:fs') as typeof import('node:fs');
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const path = require('node:path') as typeof import('node:path');

    const docsDir = fs.existsSync(path.join(process.cwd(), 'packages', 'docs'))
      ? path.join(process.cwd(), 'packages', 'docs')
      : path.join(process.cwd(), '..', 'docs');

    if (!fs.existsSync(docsDir)) return [];

    const results: string[] = [];
    function walk(dir: string, base: string): void {
      for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) walk(full, base);
        else if (entry.isFile() && entry.name.endsWith('.md')) {
          results.push(path.relative(base, full).replace(/\.md$/, '').split(path.sep).join('/'));
        }
      }
    }
    walk(docsDir, docsDir);
    return results;
  } catch {
    return [];
  }
}

// ---------- Public API ----------

/** Load a single doc by its route slug. Returns null if not found. */
export function getDocBySlug(slug: string): DocPage | null {
  const index = getIndex();
  if (index) {
    // The generated index keys are route slugs ("index", "specification", "quickstart/quickstart_ts").
    // Incoming slugs from [[...slug]] also use "index" sentinel for the root route.
    const normalized =
      slug === '' || slug === 'index' ? 'index' : slug.replaceAll(/^\/+|\/+$/g, '');
    return index.docsByRouteSlug[normalized] ?? null;
  }
  return getDocFromFs(slug);
}

/** Get all file slugs (including "index" and "foo/index" variants). */
export function getAllDocSlugs(): string[] {
  const index = getIndex();
  if (index) return index.fileSlugs;
  return getAllDocSlugsFromFs();
}

/** Get all canonical route slugs (no trailing /index, "" for root to match existing sitemap contract). */
export function getAllDocRouteSlugs(): string[] {
  const index = getIndex();
  if (index) {
    return Object.keys(index.docsByRouteSlug).map((s) => (s === 'index' ? '' : s));
  }
  return [...new Set(getAllDocSlugsFromFs().map((s) => toRouteSlug(s)))].map((s) =>
    s === 'index' ? '' : s,
  );
}

/** Load all doc pages. */
export function getAllDocs(): DocPage[] {
  const index = getIndex();
  if (index) return Object.values(index.docsByRouteSlug);
  return getAllDocRouteSlugs()
    .map((s) => getDocBySlug(s))
    .filter((d): d is DocPage => d !== null);
}
