// <auto-generated>
// GENERATED FILE - DO NOT EDIT
// </auto-generated>

namespace AidDiscovery {
  public static class Constants {
    public const string SpecVersionV1 = "aid1";
    public const string SpecVersionV2 = "aid2";
    public const string SpecVersion = "aid2";
    public static readonly string[] SupportedSpecVersions = new string[] { "aid1", "aid2" };
    // Version-specific raw record metadata. AidRecordV2 excludes legacy DNS kid/i.
    public static readonly string[] AidRecordV1CanonicalFields = new string[] { "v", "uri", "proto", "auth", "desc", "docs", "dep", "pka", "kid" };
    public static readonly string[] AidRecordV1AliasFields = new string[] { "p", "u", "a", "s", "d", "e", "k", "i" };
    public static readonly string[] AidRecordV2CanonicalFields = new string[] { "v", "uri", "proto", "auth", "desc", "docs", "dep", "pka" };
    public static readonly string[] AidRecordV2AliasFields = new string[] { "p", "u", "a", "s", "d", "e", "k" };
    public const string PROTO_A2A = "a2a";
    public const string PROTO_GRAPHQL = "graphql";
    public const string PROTO_GRPC = "grpc";
    public const string PROTO_LOCAL = "local";
    public const string PROTO_MCP = "mcp";
    public const string PROTO_OPENAPI = "openapi";
    public const string PROTO_UCP = "ucp";
    public const string PROTO_WEBSOCKET = "websocket";
    public const string PROTO_ZEROCONF = "zeroconf";
    public const string AUTH_APIKEY = "apikey";
    public const string AUTH_BASIC = "basic";
    public const string AUTH_CUSTOM = "custom";
    public const string AUTH_MTLS = "mtls";
    public const string AUTH_NONE = "none";
    public const string AUTH_OAUTH2_CODE = "oauth2_code";
    public const string AUTH_OAUTH2_DEVICE = "oauth2_device";
    public const string AUTH_PAT = "pat";
    // Error codes (numeric codes only; human-readable messages are intentionally omitted
    // from C#/Rust/Java constants — use ErrorMessages in Go/Python/TypeScript for display).
    public const int ERR_DNS_LOOKUP_FAILED = 1004;
    public const int ERR_FALLBACK_FAILED = 1005;
    public const int ERR_INVALID_TXT = 1001;
    public const int ERR_NO_RECORD = 1000;
    public const int ERR_SECURITY = 1003;
    public const int ERR_UNSUPPORTED_PROTO = 1002;
    public const string DnsSubdomain = "_agent";
    public const int DnsTtlMin = 300;
    public const int DnsTtlMax = 900;
    public static readonly string[] LocalUriSchemes = new string[] { "docker", "npx", "pip" };
  }
}