/**
 * Pre-compiles AID version metadata to TypeScript constants at build time.
 *
 * At runtime on Cloudflare Workers, we cannot read the workspace files from
 * disk. This script reads them at build time and emits a static module that
 * the `/api/version` route imports.
 *
 * Output: packages/web/src/generated/version.ts
 */
import fs from 'node:fs';
import path from 'node:path';
import { parse } from 'yaml';

type AidPackageJson = {
  version?: string;
};

type ProtocolConstants = {
  schemaVersion?: string;
};

function readSdkVersion(aidPkgPath: string): string {
  try {
    const raw = fs.readFileSync(aidPkgPath, 'utf8');
    const pkg = JSON.parse(raw) as AidPackageJson;
    return pkg.version ?? '0.0.0';
  } catch (error) {
    console.warn(`[generate-version] Failed to read ${aidPkgPath}: ${String(error)}`);
    return '0.0.0';
  }
}

function readSpecVersion(constantsPath: string): string {
  try {
    const raw = fs.readFileSync(constantsPath, 'utf8');
    const constants = parse(raw) as ProtocolConstants;
    return constants.schemaVersion ?? '0.0.0';
  } catch (error) {
    console.warn(`[generate-version] Failed to read ${constantsPath}: ${String(error)}`);
    return '0.0.0';
  }
}

function main(): void {
  // Script runs from packages/web, so aid package.json is at ../aid/package.json
  const aidPkgPath = path.resolve(__dirname, '..', '..', 'aid', 'package.json');
  const constantsPath = path.resolve(__dirname, '..', '..', '..', 'protocol', 'constants.yml');

  const sdkVersion = readSdkVersion(aidPkgPath);
  const specVersion = readSpecVersion(constantsPath);

  const outDir = path.resolve(__dirname, '..', 'src', 'generated');
  const outFile = path.join(outDir, 'version.ts');

  fs.mkdirSync(outDir, { recursive: true });

  const content = `// AUTO-GENERATED by scripts/generate-version.ts. Do not edit.
export const AID_SPEC_VERSION = ${JSON.stringify(specVersion)};
export const AID_SDK_VERSION = ${JSON.stringify(sdkVersion)};
export const AID_VERSION = AID_SPEC_VERSION;
`;
  fs.writeFileSync(outFile, content);

  console.log(
    `[generate-version] Wrote AID_SPEC_VERSION=${specVersion} AID_SDK_VERSION=${sdkVersion} → ${outFile}`,
  );
}

main();
