/**
 * Pre-compiles the AID SDK version to a TypeScript constant at build time.
 *
 * At runtime on Cloudflare Workers, we cannot read `packages/aid/package.json`
 * from disk. This script reads it at build time and emits a static module that
 * the `/api/version` route imports.
 *
 * Output: packages/web/src/generated/version.ts
 */
import fs from 'node:fs';
import path from 'node:path';

function main(): void {
  // Script runs from packages/web, so aid package.json is at ../aid/package.json
  const aidPkgPath = path.resolve(__dirname, '..', '..', 'aid', 'package.json');

  let version = '0.0.0';
  try {
    const raw = fs.readFileSync(aidPkgPath, 'utf8');
    const pkg = JSON.parse(raw) as { version?: string };
    version = pkg.version ?? '0.0.0';
  } catch (error) {
    console.warn(`[generate-version] Failed to read ${aidPkgPath}: ${String(error)}`);
  }

  const outDir = path.resolve(__dirname, '..', 'src', 'generated');
  const outFile = path.join(outDir, 'version.ts');

  fs.mkdirSync(outDir, { recursive: true });

  const content = `// AUTO-GENERATED by scripts/generate-version.ts. Do not edit.\nexport const AID_VERSION = ${JSON.stringify(version)};\n`;
  fs.writeFileSync(outFile, content);

  console.log(`[generate-version] Wrote AID_VERSION=${version} → ${outFile}`);
}

main();
